<#
.SYNOPSIS
    LeRoy — setup.ps1  (Windows bootstrap)

.DESCRIPTION
    The one command that turns your Claude Code into LeRoy. Runs the six steps
    from onboarding-and-install.md:

      1. Preflight (doctor.py) — check Claude Code / Node 18+ / Python 3.11+ / git,
         printing a clean fix for every miss.
      2. Detect existing ~\.claude, back it up, and merge core\ in additively
         (never clobbers your settings; hooks are appended).
      3. Install Python deps (from requirements.txt if present).
      4. Register the `leroy` command on PATH (per-user).
      5. Launch the interview -> leroy init.
      6. Print a friendly "you're live" card.

    Every path derives from $HOME\.claude — nothing is hardcoded.
    No secrets are read or written by this script.

.EXAMPLE
    .\setup.ps1
    .\setup.ps1 -SkipInit        # merge + install, skip the interview
#>

[CmdletBinding()]
param(
    [switch]$SkipInit,
    [switch]$SkipDeps
)

$ErrorActionPreference = "Stop"

$RepoRoot   = Split-Path -Parent $PSCommandPath
$Installer  = Join-Path $RepoRoot "installer"
$BinDir     = Join-Path $RepoRoot "bin"
$ClaudeHome = Join-Path $HOME ".claude"

function Section($t) { Write-Host ""; Write-Host "== $t ==" -ForegroundColor Cyan }
function Say($t)     { Write-Host "  $t" }

function Get-Python {
    foreach ($c in @("python", "py", "python3")) {
        $cmd = Get-Command $c -ErrorAction SilentlyContinue
        if ($cmd) { return $cmd.Source }
    }
    return $null
}

Write-Host ""
Write-Host "  Installing LeRoy — your AI company, in your terminal." -ForegroundColor Green
Write-Host "  Repo: $RepoRoot"

# --- Step 1: preflight ------------------------------------------------------
Section "1/6  Preflight check"
$py = Get-Python
if (-not $py) {
    Say "Python 3.11+ is required and wasn't found on PATH."
    Say "Install it from https://www.python.org/downloads/ (check 'Add to PATH'), then re-run setup."
    exit 1
}
& $py (Join-Path $Installer "doctor.py")
if ($LASTEXITCODE -ne 0) {
    Say "Prerequisites are missing (see above). Fix them, then re-run .\setup.ps1."
    exit $LASTEXITCODE
}

# --- Step 2: backup + additive merge ---------------------------------------
Section "2/6  Merge LeRoy into ~\.claude (backup first)"
if (Test-Path $ClaudeHome) {
    Say "Existing ~\.claude detected — it will be backed up before any change."
} else {
    Say "No existing ~\.claude — fresh install."
}
& $py (Join-Path $Installer "merge.py")
if ($LASTEXITCODE -ne 0) { Say "Merge failed. Nothing was overwritten (backup is intact)."; exit $LASTEXITCODE }

# --- Step 3: python deps ----------------------------------------------------
Section "3/6  Install Python dependencies"
$req = Join-Path $RepoRoot "requirements.txt"
if ($SkipDeps) {
    Say "Skipped (--SkipDeps)."
} elseif (Test-Path $req) {
    Say "Installing from requirements.txt..."
    & $py -m pip install --user -q -r $req
    if ($LASTEXITCODE -ne 0) { Say "pip install reported an error — continuing (installer/CLI are stdlib-only)." }
} else {
    Say "No requirements.txt — installer + CLI are stdlib-only, nothing to install."
}

# --- Step 4: register `leroy` on PATH --------------------------------------
Section "4/6  Register the 'leroy' command"
# Create a tiny shim in a user-local bin dir and add it to the user PATH.
$UserBin = Join-Path $HOME ".local\bin"
New-Item -ItemType Directory -Force -Path $UserBin | Out-Null
$Shim = Join-Path $UserBin "leroy.ps1"
$LeroyPs1 = Join-Path $BinDir "leroy.ps1"
# The shim just forwards to the repo's CLI so `leroy update` keeps it current.
@"
# LeRoy shim — forwards to the repo CLI. Auto-generated by setup.ps1.
& '$LeroyPs1' @args
"@ | Set-Content -Path $Shim -Encoding UTF8

# Also drop a .cmd wrapper so `leroy` works from cmd.exe / plain shells.
$CmdShim = Join-Path $UserBin "leroy.cmd"
@"
@echo off
powershell -NoProfile -ExecutionPolicy Bypass -File "$LeroyPs1" %*
"@ | Set-Content -Path $CmdShim -Encoding ASCII

$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if ($userPath -notlike "*$UserBin*") {
    [Environment]::SetEnvironmentVariable("Path", "$userPath;$UserBin", "User")
    Say "Added $UserBin to your user PATH (open a new terminal to pick it up)."
} else {
    Say "$UserBin already on PATH."
}
Say "Registered: leroy -> $LeroyPs1"

# --- Step 5: the interview --------------------------------------------------
Section "5/6  Get-to-know-you interview"
if ($SkipInit) {
    Say "Skipped (--SkipInit). Run 'leroy init' whenever you're ready."
} else {
    & $py (Join-Path $Installer "wizard.py")
}

# --- Step 6: you're live ----------------------------------------------------
Section "6/6  You're live"
Write-Host ""
Write-Host "  +--------------------------------------------------------------+" -ForegroundColor Green
Write-Host "  |  LeRoy is installed. Welcome aboard.                         |" -ForegroundColor Green
Write-Host "  |                                                              |" -ForegroundColor Green
Write-Host "  |   Start a session ....... leroy                              |" -ForegroundColor Green
Write-Host "  |   Health check .......... leroy doctor                       |" -ForegroundColor Green
Write-Host "  |   See your memory ....... leroy memory                       |" -ForegroundColor Green
Write-Host "  |   Desktop app (beta) .... leroy start                        |" -ForegroundColor Green
Write-Host "  |   Update later .......... leroy update                       |" -ForegroundColor Green
Write-Host "  |   Undo everything ....... leroy reset                        |" -ForegroundColor Green
Write-Host "  |                                                              |" -ForegroundColor Green
Write-Host "  |  Your memory lives at ~\.claude\memory\                      |" -ForegroundColor Green
Write-Host "  |  (Open a NEW terminal so 'leroy' is on your PATH.)           |" -ForegroundColor Green
Write-Host "  +--------------------------------------------------------------+" -ForegroundColor Green
Write-Host ""
